name: 'GraphQL Schema merge'
description: 'Merge GraphQL schema files into one string'
author: 'Philipp Staudt'

inputs:
  path:
    description: 'Glob pattern or patterns to use when loading GraphQl files'
    required: true
    default: './**/*.graphqls'
outputs:
  fileContent:
    description: 'String of merged GraphQL files'
runs:
  using: 'node12'
  main: 'dist/index.js'
