name: 'Thank You Action'
description: 'Say "Thank You" to new pull requests'
author: 'Philipp Staudt'

inputs:
  path:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  fileContent: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
